
/* Drop Tables */

DROP TABLE IF EXISTS CUOTAS_PENDIENTES;
DROP TABLE IF EXISTS VACUNAS;
DROP TABLE IF EXISTS MASCOTAS;
DROP TABLE IF EXISTS SOCIOS;
DROP TABLE IF EXISTS HORARIOS;
DROP TABLE IF EXISTS COD_HORARIOS;




/* Create Tables */

CREATE TABLE CUOTAS_PENDIENTES
(
	NRO_SOCIO numeric NOT NULL,
	FECHA_CUOTA date NOT NULL,
	DESCRIPCION varchar,
	FECHA_PAGO date,
	UNIQUE (NRO_SOCIO, FECHA_CUOTA)
) WITHOUT OIDS;


CREATE TABLE VACUNAS
(
	NRO_SOCIO numeric NOT NULL,
	NOMBRE varchar NOT NULL,
	MUERTA varchar(1) DEFAULT 'N' NOT NULL
) WITHOUT OIDS;


CREATE TABLE SOCIOS
(
	NRO_SOCIO numeric NOT NULL,
	PRIMER_NOMBRE varchar NOT NULL,
	SEGUNDO_NOMBRE varchar,
	PRIMER_APELLIDO varchar NOT NULL,
	SEGUNDO_APELLIDO varchar,
	TELEFONO varchar,
	CELULAR varchar,
	DIRECCION varchar NOT NULL,
	COBRADOR varchar(1) DEFAULT 'N' NOT NULL,
	PRIMARY KEY (NRO_SOCIO)
) WITHOUT OIDS;


CREATE TABLE COD_HORARIOS
(
	COD_DIA numeric NOT NULL,
	DESCRIPCION varchar NOT NULL,
	PRIMARY KEY (COD_DIA)
) WITHOUT OIDS;


CREATE TABLE HORARIOS
(
	COD_DIA numeric NOT NULL,
	FECHA_INICIO time NOT NULL,
	FECHA_FIN time,
	DESCRIPCION varchar,
	NRO_SOCIO numeric
) WITHOUT OIDS;


CREATE TABLE MASCOTAS
(
	NRO_SOCIO numeric NOT NULL,
	NOMBRE varchar NOT NULL,
	FECHA_NACIMIENTO date NOT NULL,
	PESO numeric,
	INFORMACION varchar,
	ESPECIE varchar NOT NULL,
	RAZA varchar NOT NULL,
	SEXO varchar(1) NOT NULL,
	MUERTA varchar(1) DEFAULT 'N' NOT NULL,
	UNIQUE (NRO_SOCIO, NOMBRE, MUERTA)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE MASCOTAS
	ADD FOREIGN KEY (NRO_SOCIO)
	REFERENCES SOCIOS (NRO_SOCIO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CUOTAS_PENDIENTES
	ADD FOREIGN KEY (NRO_SOCIO)
	REFERENCES SOCIOS (NRO_SOCIO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HORARIOS
	ADD FOREIGN KEY (COD_DIA)
	REFERENCES COD_HORARIOS (COD_DIA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE VACUNAS
	ADD FOREIGN KEY (NRO_SOCIO, NOMBRE, MUERTA)
	REFERENCES MASCOTAS (NRO_SOCIO, NOMBRE, MUERTA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



