package veterinarias.consultas.jpanels;

import java.awt.Color;
import java.awt.Font;

import javax.swing.Action;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

import veterinarias.consultas.actions.BotonBuscarSocioPorNombreAction;
import veterinarias.pruebas.ImagePanel;

public class VerSociosPorNombre extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private ImagePanel panelBusqueda;
    private JTextField textField_1;
    private JTextField textField_2;
    private JTextField textField_3;
    private JTextField textField_4;
    private final Action btnBuscarSocioPorNombreAction = new BotonBuscarSocioPorNombreAction();
    private static JPanel panel;
    private JScrollPane scrollPane;
    private static javax.swing.JTable jTable1;

    /** Creates new form VerSociosPorNombre */
    public VerSociosPorNombre() {
        initComponents();
        panelBusqueda.setVisible(true);
        panelBusqueda.setImagen("perro.jpg");
        panel.setVisible(false);
    }

    public static JPanel getPanel() {
        return panel;
    }

    public static void setJTable1(JTable jTable1) {
        VerSociosPorNombre.jTable1 = jTable1;
    }

    public static JTable getJTable1() {
        return jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        panelBusqueda = new ImagePanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        jLabel1.setText("Primer Nombre:");
        jLabel2.setText("Segundo Nombre:");
        jLabel3.setText("Primer Apellido:");
        jLabel4.setText("Segundo Apellido:");
        textField_1 = new JTextField();
        textField_1.setFont(new Font("Tahoma", Font.PLAIN, 12));
        textField_2 = new JTextField();
        textField_2.setFont(new Font("Tahoma", Font.PLAIN, 12));
        textField_3 = new JTextField();
        textField_3.setFont(new Font("Tahoma", Font.PLAIN, 12));
        textField_4 = new JTextField();
        textField_4.setFont(new Font("Tahoma", Font.PLAIN, 12));
        JButton btnBuscar = new JButton("Buscar");
        btnBuscar.setAction(btnBuscarSocioPorNombreAction);
        panel = new JPanel();
        panel.setBackground(Color.PINK);
        //jScrollPane1.setViewportView(jTable1);
        javax.swing.GroupLayout gl_panelBusqueda = new javax.swing.GroupLayout(panelBusqueda);
        gl_panelBusqueda.setHorizontalGroup(gl_panelBusqueda.createParallelGroup(Alignment.TRAILING).addGroup(
                Alignment.LEADING,
                gl_panelBusqueda
                        .createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                                gl_panelBusqueda
                                        .createParallelGroup(Alignment.LEADING)
                                        .addComponent(panel, GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                                        .addGroup(
                                                gl_panelBusqueda
                                                        .createSequentialGroup()
                                                        .addGroup(
                                                                gl_panelBusqueda.createParallelGroup(Alignment.LEADING).addComponent(jLabel1)
                                                                        .addComponent(jLabel2).addComponent(jLabel3).addComponent(jLabel4))
                                                        .addGap(64)
                                                        .addGroup(
                                                                gl_panelBusqueda
                                                                        .createParallelGroup(Alignment.TRAILING, false)
                                                                        .addComponent(textField_3, Alignment.LEADING)
                                                                        .addComponent(textField_4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 236,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(textField_2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 236,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(textField_1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 236,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap()));
        gl_panelBusqueda.setVerticalGroup(gl_panelBusqueda.createParallelGroup(Alignment.LEADING).addGroup(
                gl_panelBusqueda
                        .createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                                gl_panelBusqueda.createParallelGroup(Alignment.TRAILING).addComponent(jLabel1)
                                        .addComponent(textField_1, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addGroup(
                                gl_panelBusqueda.createParallelGroup(Alignment.BASELINE).addComponent(jLabel2)
                                        .addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addGroup(
                                gl_panelBusqueda.createParallelGroup(Alignment.TRAILING).addComponent(jLabel3)
                                        .addComponent(textField_3, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addGroup(
                                gl_panelBusqueda.createParallelGroup(Alignment.TRAILING).addComponent(jLabel4)
                                        .addComponent(textField_4, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)).addGap(18)
                        .addComponent(btnBuscar).addGap(57).addComponent(panel, GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE).addContainerGap()));
        scrollPane = new JScrollPane();
        javax.swing.GroupLayout layout3 = new javax.swing.GroupLayout(panel);
        layout3.setHorizontalGroup(layout3.createParallelGroup(Alignment.LEADING).addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE));
        layout3.setVerticalGroup(layout3.createParallelGroup(Alignment.LEADING).addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE));
        panel.setLayout(layout3);
        panelBusqueda.setLayout(gl_panelBusqueda);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(panelBusqueda, GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(panelBusqueda, GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE));
        this.setLayout(layout);
        //
        jTable1 = new JTable();
        jTable1.setBackground(Color.RED);
        //jTable1.setOpaque(false);
        scrollPane.setOpaque(false);
        panel.setOpaque(true);
        panelBusqueda.setOpaque(true);
        scrollPane.setViewportView(jTable1);
    }// </editor-fold>
}