package veterinarias.consultas.jpanels;

import java.awt.Color;
import java.awt.Font;

import javax.swing.Action;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

import veterinarias.consultas.actions.BotonBuscarSocioPorNombreAction;
import veterinarias.pruebas.ImagePanel;

public class VerSociosPorNombre extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    // Variables declaration - do not modify
    private javax.swing.JLabel lblPrimerNombre;
    private javax.swing.JLabel lblSegundoNombre;
    private javax.swing.JLabel lblPrimerApellido;
    private javax.swing.JLabel lblSegundoApellido;
    private ImagePanel panelBusqueda;
    private static JTextField txtSegundoApellido;
    private static JTextField txtPrimerApellido;
    private static JTextField txtPrimerNombre;
    private static JTextField txtSegundoNombre;
    private final Action btnBuscarSocioPorNombreAction = new BotonBuscarSocioPorNombreAction();
    private static JPanel panel;
    private JScrollPane scrollPane;
    private static javax.swing.JTable jTable1;
    private JTextField txtDireccion;
    private JTextField txtTelefono;
    private JLabel lblNroSocio;
    private JTextField txtNroSocio;
    private JTextField txtCelular;
    private JLabel lblCelular;

    /** Creates new form VerSociosPorNombre */
    public VerSociosPorNombre() {
        initComponents();
        panelBusqueda.setVisible(true);
        panelBusqueda.setImagen("perro.jpg");
        panel.setVisible(false);
    }

    public static void setTxtSegundoApellido(JTextField txtSegundoApellido) {
        VerSociosPorNombre.txtSegundoApellido = txtSegundoApellido;
    }

    public static void setTxtPrimerApellido(JTextField txtPrimerApellido) {
        VerSociosPorNombre.txtPrimerApellido = txtPrimerApellido;
    }

    public static void setTxtPrimerNombre(JTextField txtPrimerNombre) {
        VerSociosPorNombre.txtPrimerNombre = txtPrimerNombre;
    }

    public static void setTxtSegundoNombre(JTextField txtSegundoNombre) {
        VerSociosPorNombre.txtSegundoNombre = txtSegundoNombre;
    }

    public static JTextField getTxtSegundoApellido() {
        return txtSegundoApellido;
    }

    public static JTextField getTxtPrimerApellido() {
        return txtPrimerApellido;
    }

    public static JTextField getTxtPrimerNombre() {
        return txtPrimerNombre;
    }

    public static JTextField getTxtSegundoNombre() {
        return txtSegundoNombre;
    }

    public static JPanel getPanel() {
        return panel;
    }

    public static void setJTable1(JTable jTable1) {
        VerSociosPorNombre.jTable1 = jTable1;
    }

    public static JTable getJTable1() {
        return jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        panelBusqueda = new ImagePanel();
        lblPrimerNombre = new javax.swing.JLabel();
        lblPrimerNombre.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        lblSegundoNombre = new javax.swing.JLabel();
        lblSegundoNombre.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        lblPrimerApellido = new javax.swing.JLabel();
        lblPrimerApellido.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        lblSegundoApellido = new javax.swing.JLabel();
        lblSegundoApellido.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        lblPrimerNombre.setText("Primer Nombre:");
        lblSegundoNombre.setText("Segundo Nombre:");
        lblPrimerApellido.setText("Primer Apellido:");
        lblSegundoApellido.setText("Segundo Apellido:");
        txtSegundoApellido = new JTextField();
        txtSegundoApellido.setFont(new Font("Tahoma", Font.PLAIN, 12));
        txtPrimerApellido = new JTextField();
        txtPrimerApellido.setFont(new Font("Tahoma", Font.PLAIN, 12));
        txtPrimerNombre = new JTextField();
        txtPrimerNombre.setFont(new Font("Tahoma", Font.PLAIN, 12));
        txtSegundoNombre = new JTextField();
        txtSegundoNombre.setFont(new Font("Tahoma", Font.PLAIN, 12));
        JButton btnBuscar = new JButton("Buscar");
        btnBuscar.setAction(btnBuscarSocioPorNombreAction);
        panel = new JPanel();
        panel.setBorder(null);
        panel.setBackground(Color.WHITE);
        JLabel lblDireccion = new JLabel("Direcci\u00F3n:");
        lblDireccion.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        txtDireccion = new JTextField();
        txtDireccion.setColumns(10);
        JLabel lblTelefono = new JLabel("Tel\u00E9fono:");
        lblTelefono.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        txtTelefono = new JTextField();
        txtTelefono.setColumns(10);
        lblNroSocio = new JLabel("Nro Socio:");
        lblNroSocio.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        txtNroSocio = new JTextField();
        txtNroSocio.setColumns(10);
        txtCelular = new JTextField();
        txtCelular.setColumns(10);
        lblCelular = new JLabel("Celular:");
        lblCelular.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        JCheckBox chckbxCobrador = new JCheckBox("Cobrador");
        chckbxCobrador.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        //jScrollPane1.setViewportView(jTable1);
        javax.swing.GroupLayout gl_panelBusqueda = new javax.swing.GroupLayout(panelBusqueda);
        gl_panelBusqueda
                .setHorizontalGroup(gl_panelBusqueda
                        .createParallelGroup(Alignment.LEADING)
                        .addGroup(
                                gl_panelBusqueda
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                gl_panelBusqueda
                                                        .createParallelGroup(Alignment.LEADING)
                                                        .addComponent(panel, GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
                                                        .addGroup(
                                                                gl_panelBusqueda
                                                                        .createSequentialGroup()
                                                                        .addGroup(
                                                                                gl_panelBusqueda
                                                                                        .createParallelGroup(Alignment.LEADING)
                                                                                        .addGroup(
                                                                                                gl_panelBusqueda
                                                                                                        .createSequentialGroup()
                                                                                                        .addGroup(
                                                                                                                gl_panelBusqueda
                                                                                                                        .createParallelGroup(Alignment.LEADING)
                                                                                                                        .addComponent(lblPrimerApellido)
                                                                                                                        .addComponent(lblPrimerNombre)
                                                                                                                        .addComponent(lblNroSocio)
                                                                                                                        .addComponent(lblTelefono))
                                                                                                        .addGap(76)
                                                                                                        .addGroup(
                                                                                                                gl_panelBusqueda
                                                                                                                        .createParallelGroup(
                                                                                                                                Alignment.TRAILING, false)
                                                                                                                        .addComponent(txtPrimerNombre,
                                                                                                                                GroupLayout.DEFAULT_SIZE, 236,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                        .addGroup(
                                                                                                                                gl_panelBusqueda
                                                                                                                                        .createSequentialGroup()
                                                                                                                                        .addComponent(
                                                                                                                                                txtPrimerApellido)
                                                                                                                                        .addPreferredGap(
                                                                                                                                                ComponentPlacement.RELATED))
                                                                                                                        .addComponent(txtNroSocio,
                                                                                                                                GroupLayout.DEFAULT_SIZE, 236,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                        .addComponent(txtTelefono))
                                                                                                        .addGap(18)
                                                                                                        .addGroup(
                                                                                                                gl_panelBusqueda
                                                                                                                        .createParallelGroup(Alignment.LEADING)
                                                                                                                        .addComponent(lblSegundoApellido)
                                                                                                                        .addComponent(lblSegundoNombre)
                                                                                                                        .addComponent(lblDireccion)
                                                                                                                        .addComponent(lblCelular,
                                                                                                                                GroupLayout.PREFERRED_SIZE, 75,
                                                                                                                                GroupLayout.PREFERRED_SIZE)))
                                                                                        .addComponent(chckbxCobrador))
                                                                        .addGap(61)
                                                                        .addGroup(
                                                                                gl_panelBusqueda
                                                                                        .createParallelGroup(Alignment.LEADING)
                                                                                        .addGroup(
                                                                                                gl_panelBusqueda
                                                                                                        .createParallelGroup(Alignment.LEADING, false)
                                                                                                        .addComponent(txtDireccion)
                                                                                                        .addComponent(txtSegundoApellido)
                                                                                                        .addComponent(txtSegundoNombre,
                                                                                                                GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                                                                                        .addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE,
                                                                                                                89, GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(txtCelular, GroupLayout.PREFERRED_SIZE, 236,
                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(ComponentPlacement.RELATED, 130, Short.MAX_VALUE))).addContainerGap()));
        gl_panelBusqueda.setVerticalGroup(gl_panelBusqueda.createParallelGroup(Alignment.LEADING).addGroup(
                gl_panelBusqueda
                        .createSequentialGroup()
                        .addGap(34)
                        .addGroup(
                                gl_panelBusqueda.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(txtPrimerNombre, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSegundoNombre, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPrimerNombre).addComponent(lblSegundoNombre))
                        .addGap(19)
                        .addGroup(
                                gl_panelBusqueda
                                        .createParallelGroup(Alignment.TRAILING)
                                        .addGroup(
                                                gl_panelBusqueda.createParallelGroup(Alignment.BASELINE)
                                                        .addComponent(txtPrimerApellido, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblPrimerApellido).addComponent(lblSegundoApellido))
                                        .addComponent(txtSegundoApellido, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addGap(20)
                        .addGroup(
                                gl_panelBusqueda.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(txtDireccion, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE).addComponent(lblDireccion)
                                        .addComponent(txtNroSocio, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE).addComponent(lblNroSocio))
                        .addGap(18)
                        .addGroup(
                                gl_panelBusqueda.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(txtTelefono, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE).addComponent(lblTelefono)
                                        .addComponent(lblCelular, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCelular, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)).addGap(21)
                        .addGroup(gl_panelBusqueda.createParallelGroup(Alignment.BASELINE).addComponent(btnBuscar).addComponent(chckbxCobrador)).addGap(18)
                        .addComponent(panel, GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE).addContainerGap()));
        scrollPane = new JScrollPane();
        scrollPane.setBorder(null);
        scrollPane.setViewportBorder(null);
        javax.swing.GroupLayout layout3 = new javax.swing.GroupLayout(panel);
        layout3.setHorizontalGroup(layout3.createParallelGroup(Alignment.LEADING).addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE));
        layout3.setVerticalGroup(layout3.createParallelGroup(Alignment.TRAILING).addGroup(
                layout3.createSequentialGroup().addContainerGap(70, Short.MAX_VALUE)
                        .addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 357, GroupLayout.PREFERRED_SIZE)));
        panel.setLayout(layout3);
        panelBusqueda.setLayout(gl_panelBusqueda);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(panelBusqueda, GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(panelBusqueda, GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE));
        this.setLayout(layout);
        //
        jTable1 = new JTable();
        //scrollPane.setOpaque(false);
        panel.setOpaque(false);
        scrollPane.setViewportView(jTable1);
        scrollPane.setOpaque(false);
        scrollPane.getViewport().setOpaque(false);
    }// </editor-fold>
}