package veterinarias.consultas.jpanels;

import java.awt.Color;
import java.awt.Font;

import javax.swing.Action;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

import veterinarias.consultas.actions.BotonBuscarSocioPorNombreAction;
import veterinarias.pruebas.ImagePanel;

public class VerSociosPorNombre extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    // Variables declaration - do not modify
    private javax.swing.JLabel lblPrimerNombre;
    private javax.swing.JLabel lblSegundoNombre;
    private javax.swing.JLabel lblPrimerApellido;
    private javax.swing.JLabel lblSegundoApellido;
    private ImagePanel panelBusqueda;
    private static JTextField txtSegundoApellido;
    private static JTextField txtPrimerApellido;
    private static JTextField txtPrimerNombre;
    private static JTextField txtSegundoNombre;
    private final Action btnBuscarSocioPorNombreAction = new BotonBuscarSocioPorNombreAction();
    private static JPanel panel;
    private JScrollPane scrollPane;
    private static javax.swing.JTable jTable1;

    /** Creates new form VerSociosPorNombre */
    public VerSociosPorNombre() {
        initComponents();
        panelBusqueda.setVisible(true);
        panelBusqueda.setImagen("perro.jpg");
        panel.setVisible(false);
    }

    public static void setTxtSegundoApellido(JTextField txtSegundoApellido) {
        VerSociosPorNombre.txtSegundoApellido = txtSegundoApellido;
    }

    public static void setTxtPrimerApellido(JTextField txtPrimerApellido) {
        VerSociosPorNombre.txtPrimerApellido = txtPrimerApellido;
    }

    public static void setTxtPrimerNombre(JTextField txtPrimerNombre) {
        VerSociosPorNombre.txtPrimerNombre = txtPrimerNombre;
    }

    public static void setTxtSegundoNombre(JTextField txtSegundoNombre) {
        VerSociosPorNombre.txtSegundoNombre = txtSegundoNombre;
    }

    public static JTextField getTxtSegundoApellido() {
        return txtSegundoApellido;
    }

    public static JTextField getTxtPrimerApellido() {
        return txtPrimerApellido;
    }

    public static JTextField getTxtPrimerNombre() {
        return txtPrimerNombre;
    }

    public static JTextField getTxtSegundoNombre() {
        return txtSegundoNombre;
    }

    public static JPanel getPanel() {
        return panel;
    }

    public static void setJTable1(JTable jTable1) {
        VerSociosPorNombre.jTable1 = jTable1;
    }

    public static JTable getJTable1() {
        return jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        panelBusqueda = new ImagePanel();
        lblPrimerNombre = new javax.swing.JLabel();
        lblPrimerNombre.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        lblSegundoNombre = new javax.swing.JLabel();
        lblSegundoNombre.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        lblPrimerApellido = new javax.swing.JLabel();
        lblPrimerApellido.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        lblSegundoApellido = new javax.swing.JLabel();
        lblSegundoApellido.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
        lblPrimerNombre.setText("Primer Nombre:");
        lblSegundoNombre.setText("Segundo Nombre:");
        lblPrimerApellido.setText("Primer Apellido:");
        lblSegundoApellido.setText("Segundo Apellido:");
        txtSegundoApellido = new JTextField();
        txtSegundoApellido.setFont(new Font("Tahoma", Font.PLAIN, 12));
        txtPrimerApellido = new JTextField();
        txtPrimerApellido.setFont(new Font("Tahoma", Font.PLAIN, 12));
        txtPrimerNombre = new JTextField();
        txtPrimerNombre.setFont(new Font("Tahoma", Font.PLAIN, 12));
        txtSegundoNombre = new JTextField();
        txtSegundoNombre.setFont(new Font("Tahoma", Font.PLAIN, 12));
        JButton btnBuscar = new JButton("Buscar");
        btnBuscar.setAction(btnBuscarSocioPorNombreAction);
        panel = new JPanel();
        panel.setBorder(null);
        panel.setBackground(Color.WHITE);
        //jScrollPane1.setViewportView(jTable1);
        javax.swing.GroupLayout gl_panelBusqueda = new javax.swing.GroupLayout(panelBusqueda);
        gl_panelBusqueda.setHorizontalGroup(gl_panelBusqueda.createParallelGroup(Alignment.LEADING).addGroup(
                gl_panelBusqueda
                        .createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                                gl_panelBusqueda
                                        .createParallelGroup(Alignment.LEADING)
                                        .addComponent(panel, GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
                                        .addGroup(
                                                gl_panelBusqueda
                                                        .createSequentialGroup()
                                                        .addGroup(
                                                                gl_panelBusqueda.createParallelGroup(Alignment.LEADING).addComponent(lblPrimerNombre)
                                                                        .addComponent(lblSegundoNombre).addComponent(lblPrimerApellido)
                                                                        .addComponent(lblSegundoApellido))
                                                        .addGap(64)
                                                        .addGroup(
                                                                gl_panelBusqueda
                                                                        .createParallelGroup(Alignment.TRAILING, false)
                                                                        .addComponent(txtPrimerApellido, Alignment.LEADING)
                                                                        .addComponent(txtSegundoApellido, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 236,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(txtSegundoNombre, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 236,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(txtPrimerNombre, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 236,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap()));
        gl_panelBusqueda.setVerticalGroup(gl_panelBusqueda.createParallelGroup(Alignment.LEADING).addGroup(
                gl_panelBusqueda
                        .createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                                gl_panelBusqueda.createParallelGroup(Alignment.TRAILING).addComponent(lblPrimerNombre)
                                        .addComponent(txtPrimerNombre, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addGroup(
                                gl_panelBusqueda.createParallelGroup(Alignment.BASELINE).addComponent(lblSegundoNombre)
                                        .addComponent(txtSegundoNombre, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addGroup(
                                gl_panelBusqueda.createParallelGroup(Alignment.TRAILING).addComponent(lblPrimerApellido)
                                        .addComponent(txtPrimerApellido, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addGroup(
                                gl_panelBusqueda.createParallelGroup(Alignment.TRAILING).addComponent(lblSegundoApellido)
                                        .addComponent(txtSegundoApellido, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)).addGap(18)
                        .addComponent(btnBuscar).addGap(57).addComponent(panel, GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE).addContainerGap()));
        scrollPane = new JScrollPane();
        scrollPane.setBorder(null);
        scrollPane.setViewportBorder(null);
        javax.swing.GroupLayout layout3 = new javax.swing.GroupLayout(panel);
        layout3.setHorizontalGroup(layout3.createParallelGroup(Alignment.LEADING).addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE));
        layout3.setVerticalGroup(layout3.createParallelGroup(Alignment.LEADING).addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE));
        panel.setLayout(layout3);
        panelBusqueda.setLayout(gl_panelBusqueda);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(panelBusqueda, GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(panelBusqueda, GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE));
        this.setLayout(layout);
        //
        jTable1 = new JTable();
        //scrollPane.setOpaque(false);
        panel.setOpaque(false);
        scrollPane.setViewportView(jTable1);
        scrollPane.setOpaque(false);
        scrollPane.getViewport().setOpaque(false);
    }// </editor-fold>
}